title: <p align="center"> Carolyn Liu </p>

logo: "/images/CL_headshot.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CarolynLiu_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/carolynliu4/">LinkedIn</a> |
  <a href="https://github.com/Crliu4">GitHub</a>
  </p>
  
  <p align="justify">
  Currently an MS candidate in Computational Analysis & Public Policy @ UChicago graduating in June 2023. 
  I am passionate about using data science and machine learning to address social issues.
  <br></br>
  Most recently, I was a Data Fellow at the US Census Bureau where I created a pipeline to improve one of 
  their newest data products, Business Formation Statistics. In my previous life, I was an accounting and 
  economics researcher at Harvard Business School.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-LY6683ZLYC