title: <p align="center"> Carolyn Liu </p>

logo: "/images/IMG_7084.JPG?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/carolynliu4/">LinkedIn</a> |
  <a href="https://github.com/Crliu4">GitHub</a>
  </p>
  
  <p align="justify">
  M.S. candidate in Computational Analysis and Public Policy @ UChicago
  <br><br>
  I am currently a Data Fellow at the U.S. Census Bureau.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

#<a href="pdf/resume.pdf">Resume</a> |