title: Carolyn Liu # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. Candidate in Computational Analysis and Public Policy @ UChicago 
  <br><br>
  <p align="center">
  <a href="https://www.linkedin.com/in/carolynliu4/">LinkedIn</a> |
  <a href="https://github.com/crliu4">GitHub</a>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
