title: <p align="center"> Carolyn Liu </p>

logo: "/images/CL_headshot.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CarolynLiu_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/carolynliu4/">LinkedIn</a> |
  <a href="https://github.com/Crliu4">GitHub</a>
  </p>
  
  #<p align="justify">
  <p align="center">
  M.S. candidate in Computational Analysis and Public Policy @ UChicago
  <br><br>
  Most recently a Data Fellow at the U.S. Census Bureau.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal