title: <p align="center"> Carolyn Liu </p>

logo: "/images/CL_headshot.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CarolynLiu_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/carolynliu4/">LinkedIn</a> |
  <a href="https://github.com/Crliu4">GitHub</a>
  </p>
  
  <p align="justify">
  MS candidate in Computational Analysis & Public Policy @ UChicago graduating June 2023. 
  Passionate about using data science and machine learning to address social issues.
  Most recently a Data Fellow at the US Census Bureau.
 
  </p>
  
theme: jekyll-theme-minimal